### ISSUE TITLE
Issue with .NET samples

### ISSUE THREAD

**Issue by micheleissa** [ibm-messaging/mq-dev-patterns#19]
Hi,
I've a local container instance of IBM MQ running, I configured the ```env.json``` accordingly and pointed the reference for IBM.XMS.dll to local one downloaded per the instructions in README file.
I keep getting an exception trying any sample file
![image](https://user-images.githubusercontent.com/16201881/95503146-8b1f3f00-0970-11eb-9406-099f92af0bbf.png)

Any help is much appreciated.

**Comment by chughts** [comment]
Based on the logs it looks like the error is occurring on the line
````
connectionWMQ = cf.CreateConnection();
````

The factory, factory instances have been created, so it doesn't appear to be a problem with the dlls, though I am not ruling that out.

Prior to that line the connection properties are set, and it could be that one of the properties in that is causing the problem. The logs suggest all the fields are set correctly. As you have multiple connections set in the .json file, that will set a connection string `XMSC.WMQ_CONNECTION_NAME_LIST`, maybe that is causing the problem. The servers don't all need to be running - as that is the purpose of the multiple connections. Although I don't think I have tested when none of them are available. 

Could you modify the .json file to remove the 2nd and 3rd connections, leaving just the one. This will push the connection logic down setting host and port rather than a connection name list.

**Comment by chughts** [comment]
There are a couple of links that suggest that this issue could be related to credentials or certificates.

https://www.ibm.com/support/pages/apar/IC68152
https://www.ibm.com/support/pages/apar/IJ04255

You are not setting any TLS options, so certificates aren't being used here. So it could be down to the userid / password. 

Which brings me to the the docker image. If you run:
```
docker image inspect <your image id> --format '{{.ContainerConfig.Labels.version}}'
```
and it reports 9.1.5 or above, then I think we have fallen foul of https://stackoverflow.com/questions/61373195/ibmcom-mq-docker-image-backward-compatibility-issue/62192274#62192274

in that the app user doesn't exist. 

Instead of using
FROM ibmcom/mq:latest

we need the image to be on 
FROM ibmcom/mq:9.1.4.0-r1

at the latest.

**Comment by micheleissa** [comment]
> There are a couple of links that suggest that this issue could be related to credentials or certificates.
> 
> https://www.ibm.com/support/pages/apar/IC68152
> https://www.ibm.com/support/pages/apar/IJ04255
> 
> You are not setting any TLS options, so certificates aren't being used here. So it could be down to the userid / password.
> 
> Which brings me to the the docker image. If you run:
> 
> ```
> docker image inspect <your image id> --format '{{.ContainerConfig.Labels.version}}'
> ```
> 
> and it reports 9.1.5 or above, then I think we have fallen foul of https://stackoverflow.com/questions/61373195/ibmcom-mq-docker-image-backward-compatibility-issue/62192274#62192274
> 
> in that the app user doesn't exist.
> 
> Instead of using
> FROM ibmcom/mq:latest
> 
> we need the image to be on
> FROM ibmcom/mq:9.1.4.0-r1
> 
> at the latest.

So I have another code base that is using dotnet standards nuget package and connects fine with ```app user``` which means the user exists inside the container instance.

**Comment by micheleissa** [comment]
@chughts any inputs on that?

**Comment by chughts** [comment]
Are you saying that your other code base is connecting to the same docker container as the failing code base. If so what is the difference between the code bases?

If it's not the same docker container that they are connecting to, can you point your working code base at the failing docker container? 

On a related note,  did you issue `docker run` for the image with the parameter
`-e MQ_APP_PASSWORD=...` 

For images 9.1.5.0-r1 to current latest (.2.0.0-r2) that is the way to set the app user password, because the app user is no longer an OS user.

**Comment by micheleissa** [comment]
> Are you saying that your other code base is connecting to the same docker container as the failing code base. If so what is the difference between the code bases?
> 
> If it's not the same docker container that they are connecting to, can you point your working code base at the failing docker container?
> 
> On a related note, did you issue `docker run` for the image with the parameter
> `-e MQ_APP_PASSWORD=...`
> 
> For images 9.1.5.0-r1 to current latest (.2.0.0-r2) that is the way to set the app user password, because the app user is no longer an OS user.

The difference between them as mentioned above, I'm using the .NET standard NuGet library from [here](https://www.nuget.org/packages/IBMXMSDotnetClient/)

**Comment by chughts** [comment]
OK, let me get this right. The only difference is the DLL. The code is the same, the server is the same. The DLL should actually be the same, the difference being how it is obtained, and maybe the version of the DLL is different.

There will be differences will be in your `packages.config` and the `.csprog` files.

I am guessing that your `packages.config` file has an extra line. The one in this repo is

````
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Newtonsoft.Json" version="12.0.2" targetFramework="net472" />
</packages>
````

Please post the contents of your `packages.config` so I can compare. 

The repo `.csprog` file has 
````
    <Reference Include="IBM.XMS, Version=9.1.2.0, Culture=neutral, PublicKeyToken=d2666ab12fca862b, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>C:\Program Files\IBM\MQ\bin\IBM.XMS.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed, processorArchitecture=MSIL">
      <HintPath>packages\Newtonsoft.Json.12.0.2\lib\net45\Newtonsoft.Json.dll</HintPath>
    </Reference>
````

Note that the last time this project was run it was using 9.1.2.0. I am guessing that you have 9.2.1.x. Again please post the relevant Reference section from your `.csprog` file so I can compare.

**Comment by micheleissa** [comment]
@chughts  I'm using .NET core console application so there is no packages.config file but I will post the content of ```.csproj``` files.

**Comment by micheleissa** [comment]
@chughts I was wrong my code with the nuget library does not work either I'm getting this error:
```
There are 3 connections
Connection string is localhost(1414),192.168.252.1(1416),192.168.252.1(1415)
Connection Cipher is set to
Key Repository is set to
XMSException caught: IBM.XMS.XMSException: CWSMQ0008E: XMSC_WMQ_CONNECTION_MODE is not supported in this release.
The application has attempted to use a feature or capability that is not supported by the current release of the software.
Remove the code that attempts to use this capability or update to a later release of the software if available.
   at IBM.XMS.Client.WMQ.Factories.WmqConnectionFactory.CreateProviderConnection(XmsPropertyContext connectionProps)
   at IBM.XMS.Client.Impl.XmsConnectionFactoryImpl.CreateConnection(String userID, String password)
   at IBM.XMS.Client.Impl.XmsConnectionFactoryImpl.CreateConnection()
   at con_ibmmq.SimplePublisher.SendMessage() in C:\GitRepos\ibm-mq\test-app\con-ibmmq\SimplePublisher.cs:line 61
   at con_ibmmq.SimplePublisher.Pub() in C:\GitRepos\ibm-mq\test-app\con-ibmmq\SimplePublisher.cs:line 20
Sample execution  FAILED!
```
Which is a different error that yours, the docker container version is the latest
I also tried my code with the version you suggested up in the discussion: ```mq:9.1.4.0-r1``` and I get the same error 
I get the error in your sample with both versions.

**Comment by micheleissa** [comment]
@chughts 
After a lot of digging into the disassembled code and turning on full logging, I managed to find the issue. The value of this property ```XMSC.WMQ_CONNECTION_MODE``` is set incorrectly
https://github.com/ibm-messaging/mq-dev-patterns/blob/36e52bc9a96d070eda940a3b4191dd01cb0fbae2/dotnet/connPropBuilder.cs#L82

According to IBM MQ documentation in this [link ](https://www.ibm.com/support/knowledgecenter/SSFKSJ_7.5.0/com.ibm.mq.msc.doc/prx_wmq_conn_mode.htm)for **managed** code we should set it to 
```XMSC.WMQ_CM_CLIENT```
So after I changed it everything is now working fine for the sample code and my own code for the container versions latest and the one you suggested. Was there a reason why this was set to unmanaged?
Should I push a pull request to fix that line?

**Comment by chughts** [comment]
If you can create a pull request that will be great, though I think it is the if statement on line 76 that is most likely to require correcting.

````
            if (conn.key_repository != null && (conn.key_repository.Contains("*SYSTEM") || conn.key_repository.Contains("*USER")))
````

**Comment by micheleissa** [comment]
@chughts ok, I see your point. I will create a PR shortly.

**Comment by chughts** [comment]
Fixed in #27
